### ISSUE TITLE
Add RoutePatterns method

### ISSUE THREAD

**Issue by kosmazyg** [helloitsjoe/mbta-client#23]
Hi Joe,

I noticed that you don't have a RoutePatterns method defined. Do you have a helper function that I missed? 

Thanks,

Kosma

**Comment by helloitsjoe** [comment]
Hi @kosmazyg !

Thanks for pointing that out, I'm not sure if I missed that or if it wasn't part of the API when I created this library. On further inspection it looks like I'm missing `lines` as well, and the casing is outdated (`live-facilities` should be `live_facilities` according to [the changelog](https://www.mbta.com/developers/v3-api/changelog)).

I'll make these changes as soon as I can, let me know if you'd like to contribute a PR in the meantime!

**Comment by helloitsjoe** [comment]
Decided to tackle this right now, I'll close this issue but feel free to re-open or open a new one if there's anything still unresolved 👍
